"""Preferences browser behavior for the library page."""

from __future__ import annotations


def library_preferences_script() -> str:
    """Return settings loading and persistence behavior for the library scope."""
    return r'''
    const settingsDialog = $("#settings-dialog"); async function loadSettings() { const settings = await api("/api/textstrata/settings"); const presentation = settings.presentation || {}; $("#revision-limit").value = settings.revision_limit; $("#design-skin").value = presentation.skin || "paper"; $("#design-accent").value = presentation.accent || "teal"; $("#design-density").value = presentation.density || "comfortable"; $("#design-width").value = presentation.content_width || "wide"; $("#design-cards").value = presentation.card_style || "soft"; $("#design-scale").value = presentation.font_scale || 100; $("#design-scale-output").textContent = `${presentation.font_scale || 100}%`; $("#design-motion").checked = (presentation.motion || "system") === "reduced"; } async function openSettings() { if (settingsDialog && !settingsDialog.open) settingsDialog.showModal(); try { await loadSettings(); } catch (error) { toast(error.message || "Could not load settings", "error"); } } $("#settings-open")?.addEventListener("click", openSettings); $("#design-scale")?.addEventListener("input", () => { $("#design-scale-output").textContent = `${$("#design-scale").value}%`; }); $("#design-save")?.addEventListener("click", async () => { const presentation = {skin: $("#design-skin").value, accent: $("#design-accent").value, density: $("#design-density").value, content_width: $("#design-width").value, card_style: $("#design-cards").value, font_scale: +$("#design-scale").value, motion: $("#design-motion").checked ? "reduced" : "system"}; try { await api("/api/textstrata/settings", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({presentation})}); toast("Appearance saved, reloading...", "success"); setTimeout(() => location.reload(), 200); } catch (error) { toast(error.message, "error"); } }); $("#settings-save")?.addEventListener("click", async () => { try { await api("/api/textstrata/settings", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({revision_limit: +$("#revision-limit").value})}); toast("Settings saved", "success"); } catch (error) { toast(error.message, "error"); } });
'''
